#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "commands.c"

task main()
{
	initializeSystem();
	openClaw();
	wait1Msec(100);
	moveForward(37);
	wait1Msec(100);
	turn(-90);
	wait1Msec(100);
	moveForward(37);
	wait1Msec(100);
	closeClaw();
	wait1Msec(250);
	moveArm(400);
	wait1Msec(100);
	moveForward(-37);
	wait1Msec(100);
	turn(90);
	wait1Msec(250);
	moveForward(37);
	wait1Msec(100);
	moveArm(-400);
	wait1Msec(100);
	openClaw();
	wait1Msec(100);
	moveForward(-37);
	wait1Msec(100);
	turn(90);
	wait1Msec(100);
	moveForward(37);
	wait1Msec(100);
	closeClaw();
	wait1Msec(250);
	turn(180);
	wait1Msec(100);
	moveForward(74);
	wait1Msec(100);
	openClaw();


	resetSystem();
}
