#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "commands.c"

task main() {
	initializeSystem();

    openClaw();
    moveForward(100);
    wait1Msec(350);
    moveToPosition(90);
    wait1Msec(350);

    moveForward(100);
    wait1Msec(350);
    closeClaw();
    moveArm(400);

    moveForward(100);
    wait1Msec(350);
    moveToPosition(180);
    wait1Msec(350);
    
    moveToPosition(270);
    wait1Msec(350);

    moveForward(190);
    moveArm(-400);
    wait1Msec(350);
    openClaw();
    moveArm(400);

    moveToPosition(0);
    moveArm(-400);

	resetSystem();
}
