#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{
	//Program begins, insert code within curly braces
	motor[leftMotor] = 50;
	motor[rightMotor] = 50;

	wait1Msec(500);

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
