#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define DRIVE_TRAIN_SPEED 50
#define SPEED_PER_SECOND 39 //At speed 50
#define DRIVE_TRAIN_ANGLE 90
#define ARM_SPEED 20
#define CLAW_SPEED 40
#define COMPENSATION 0.728


static int driveTrainSpeed = 0;
static int driveTrainAngle = 0;
static int armSpeed = 0;
static int armPosition = 0;
static int clawSpeed = 0;
static int clawPosition = 0;


/* DriveTrain -0Functions */
void setDriveTrainSpeed(int speed) {
	driveTrainSpeed = speed;
}

void setDriveTrainAngle(int angle) {
	driveTrainAngle = angle;
}

void stopDriveTrain() {
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

void startDrivetrain(){
	motor[leftMotor] = driveTrainSpeed;
	motor[rightMotor] = driveTrainSpeed * COMPENSATION;

}

// dist is in cm
// return is in milliseconds
float calculateTravelTime(float dist) {
	float distIn1Sec = 91.1753 * (log(driveTrainSpeed + 5.15744) / log(10)) - 122.446;
	return (dist / distIn1Sec) * 1000 * 0.85;
}


/* Arm Functions */
void setArmSpeed(int speed) {
	armSpeed = speed;
}

void setArmPosition(int degrees) {
		armPosition = degrees;
}

void stopArm() {
	motor[armMotor] = 0;
}


/* Claw Functions */
void setClawSpeed(int speed) {
	clawSpeed = speed;
}

void setClawPosition(int degrees) {
	clawPosition = degrees;
}

void stopClaw() {
	motor[clawMotor] = 0;
}


/* Robot Reset */
void resetSystem() {
	stopDriveTrain();
	setDriveTrainAngle(0);
	setDriveTrainSpeed(0);

	stopArm();
	setArmSpeed(0);

	stopClaw();
	setClawSpeed(0);
}

/* Robot Initializer */
void initializeSystem() {
	setDriveTrainSpeed(DRIVE_TRAIN_SPEED);
	setDriveTrainAngle(DRIVE_TRAIN_ANGLE); // robot points north
	stopDriveTrain();
	setArmSpeed(ARM_SPEED);
	setArmPosition(0);
	stopArm();
	setClawSpeed(CLAW_SPEED);
	setClawPosition(0);
	stopClaw();
}
